[WORK IN PROGRESS DO NOT USE!]: Quick commit for rtomayko to see the issues. Non-working tests, due to [ NameError: undefined local variable or method `options' for #<Class:0x10592e4> ] in the test suite.